#include <windows.h>
#include <cocos2d.h>
#include <MinHook.h>
#include <fstream>
#include <gd.h>
#include <iostream>
#include <string>
#include <conio.h>
#include <commdlg.h>
#include <stdio.h>      
#include <stdlib.h>     
#include <random>
#include <chrono>
#include <fstream>
#include <filesystem>
#include <sstream>
#include <iomanip>
#include <fstream>
#include <algorithm>
#include <windows.h>
#include <io.h>
#include <limits>
#include <fstream>
#include <fstream>
#include <Wininet.h>
#include <urlmon.h>
#include <shellapi.h>

#include "layers/infoLayer.cpp"